name: "Request Reviewers"

description: "This is a GitHub action for adding reviewers to your PRs. You can add teams and individuals as reviewers by Labels."

inputs:
  GITHUB_TOKEN:
    description: "This is the GITHUB_TOKEN"
    required: true
  config_path:
    description: "This is where the config file is located"
    required: true
  codeowners_path:
    description: "This is where the CODEOWNERS file is located"
    required: false

runs:
  using: node16
  main: "dist/index.js"

branding:
  icon: users
  color: white
